<?php

/**
 * Jobsteps
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-07-03, 10:38:59
 */
class JobSteps extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Column(type="integer", length=10, nullable=false)
     */
    public $uid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $uidJob;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $stepName;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $namespace;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $class;

    /**
     *
     * @var integer
     * @Column(type="integer", length=5, nullable=false)
     */
    public $position;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $enabled;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $updateAt;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("autoCron");
        $this->hasMany('uid', 'JobStepExecutions', 'uidStep', ['alias' => 'JobStepExecutions']);
        $this->hasMany('uid', 'JobStepParameterLinks', 'uidStep', ['alias' => 'JobStepParameterLinks']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'JobSteps';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return JobSteps[]|JobSteps
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return JobSteps
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
