<?php

/**
 * Jobstepparameters
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-07-05, 09:09:29
 */
class JobStepParameters extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Column(type="integer", length=10, nullable=false)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $paramKey;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $value;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $enabled;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $updateAt;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("autoCron");
        $this->hasMany('uid', 'JobStepParameterLinks', 'uidParameter', ['alias' => 'JobStepParameterLinks']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'jobStepParameters';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return jobStepParameters[]|jobStepParameters
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return jobStepParameters
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
